DevOps/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^continuousdelivery/', include('continuousdelivery.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': 'accounts:index'}, name='logout'),
]

accounts/urls.py
# coding=utf-8

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update_user/$', views.update_user, name='update_user'),
    url(r'^update_password/$', views.update_password, name='update_password'),
    url(r'^register/$', views.register, name='register'),
]

accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Nickname / User', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Enter a valid username.'
                'This value must contain only letters, numbers '
                'and the characters: @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='A short name that will be used to uniquely identify'
    )
    name = models.CharField('Name', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Team', default=False)
    is_active = models.BooleanField('Active', default=True)
    date_joined = models.DateTimeField('Entry date', auto_now_add=True)
    repository_user = models.CharField('Repository user', max_length=100, blank=True)
    repository_password = models.CharField('Repository password', max_length=100, blank=True)
    vpn_user = models.CharField('VPN user', max_length=100, blank=True)
    vpn_password = models.CharField('VPN password', max_length=100, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

accounts/forms.py
# coding=utf-8

from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User


class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'is_active', 'is_staff']
        widgets = {
            'repository_password': forms.PasswordInput(render_value=True),
            'vpn_password': forms.PasswordInput(render_value=True),
        }

accounts/views.py
# coding=utf-8
from django import forms
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView
)
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm

from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/index.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email', 'repository_user', 'repository_password', 'vpn_user', 'vpn_password']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user

    def get_form(self, form_class=None):
        form = super(UpdateUserView, self).get_form(form_class)
        form.fields['repository_password'].widget = forms.PasswordInput(render_value=True)
        form.fields['vpn_password'].widget = forms.PasswordInput(render_value=True)
        return form


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'accounts/update_password.html'
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)


index = IndexView.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()

accounts/templates/accounts/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Minha Conta{% endblock %}
{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'accounts:index' %}">Home</a></li>
  <li class="active">Options</li>
</ol>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
            <a href="{% url 'accounts:index' %}" class="list-group-item active">Options</a>
            <a href="{% url 'accounts:update_user' %}" class="list-group-item">Update user</a>
            <a href="{% url 'accounts:update_password' %}" class="list-group-item">Update password</a>
            <a href="{% url 'archivebinaries' %}" class="list-group-item">Archive Binaries</a>
            <a href="{% url 'deploy' %}" class="list-group-item">Deploy</a>
            <a href="{% url 'viewlog' %}" class="list-group-item">System Log</a>
            <a href="{% url 'logout' %}" class="list-group-item">Logout</a>
        </div>

        <div class="row text-center">
            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <a href="#" id="pop">
                        <img id="imageresource" src="{% static 'img/continuous-delivery.png' %}" alt="">
                    </a>

                    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel"></h4>
                          </div>
                          <div class="modal-body">
                            <img src="" id="imagepreview" style="width: 470px; height: 345px;" >
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>

                     <script>
                        $("#pop").on("click", function() {
                           $('#imagepreview').attr('src', $('#imageresource').attr('src')); // here asign the image to the modal when the user click the enlarge link
                           $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function
                        });
                    </script>

                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        {% block accounts_container %}
            <h2>Welcome {{ user }}</h2>
        {% endblock %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Login | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Login</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Register | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Register</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Update password{% endblock %}

{% block accounts_container %}
    <h2>Update password</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/accounts/update_user.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %}Update user{% endblock %}

{% block accounts_container %}
    <h2>Update user</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}